export const theme = {
  colors: {
    primary: '#4A7CF7',
    primaryLight: '#EEF2FF',
    navy: '#1E293B',
    orange: '#F97316',
    orangeLight: '#FFF7ED',
    green: '#22C55E',
    greenLight: '#F0FDF4',
    purple: '#A855F7',
    purpleLight: '#FAF5FF',
    yellow: '#EAB308',
    yellowLight: '#FEFCE8',
    background: '#F1F5F9',
    card: '#FFFFFF',
    text: '#0F172A',
    textSecondary: '#64748B',
    textMuted: '#94A3B8',
    border: '#E2E8F0',
    white: '#FFFFFF',
    error: '#EF4444',
    errorLight: '#FEF2F2',
    success: '#22C55E',
    warning: '#F97316',
    gradientStart: '#2196C9',
    gradientEnd: '#5BC8F5',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
  },
  borderRadius: {
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
    full: 999,
  },
  typography: {
    h1: { fontSize: 30, fontWeight: '700' as const },
    h2: { fontSize: 24, fontWeight: '700' as const },
    h3: { fontSize: 20, fontWeight: '600' as const },
    h4: { fontSize: 17, fontWeight: '600' as const },
    body: { fontSize: 15, fontWeight: '400' as const },
    bodyMedium: { fontSize: 15, fontWeight: '500' as const },
    bodySmall: { fontSize: 13, fontWeight: '400' as const },
    label: { fontSize: 12, fontWeight: '600' as const },
    caption: { fontSize: 11, fontWeight: '400' as const },
  },
  shadows: {
    card: {
      shadowColor: '#0F172A',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.06,
      shadowRadius: 6,
      elevation: 2,
    },
    medium: {
      shadowColor: '#0F172A',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.1,
      shadowRadius: 12,
      elevation: 5,
    },
    fab: {
      shadowColor: '#4A7CF7',
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.35,
      shadowRadius: 10,
      elevation: 10,
    },
  },
};
